version: '3.7'

services:
  api:
    container_name: 'api'
    environment:
      ConnectionStrings:postgres: Host=postgres;Pooling=true;Database=OrderManager;User Id=root;Password=root;Include Error Detail=true;Maximum Pool Size=90;
    ports:
      - "5227:80"
    build:
      context: .
      dockerfile: src/OrderManager/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=OrderManager
    ports:
      - "5432:5432"

  client:
    container_name: 'blazor'
    build:
      context: .
      dockerfile: src/OrderManager.Client/Dockerfile
    ports:
      - "5018:80"
    depends_on:
      - api

  migrator:
    image: order-manager.migrator
    environment:
      ConnectionStrings:postgres: Host=postgres;Pooling=true;Database=OrderManager;User Id=root;Password=root;Include Error Detail=true;Maximum Pool Size=90;
    build:
      context: .
      dockerfile: src/OrderManager.Migrator/Dockerfile
    depends_on:
      - postgres

